[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing by redirecting all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration (these will be overridden by Netlify UI settings)
[build.environment]
  NODE_VERSION = "20"

# Set up headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Custom build plugin
[[plugins]]
  package = "./netlify/plugins" 